#!/bin/bash -e

# Do we want to modify the config first with the script?
[ -f /etc/service/postfix/run.config ] && source /etc/service/postfix/run.config

if [ -n "$MAILNAME" ]; then
  echo "$MAILNAME" > /etc/mailname
  postconf -e myhostname="$MAILNAME"
fi

if [ -n "$MY_NETWORKS" ]; then
  postconf -e mynetworks="$MY_NETWORKS"
fi

if [ -n "$MY_DESTINATION" ]; then
  postconf -e mydestination="$MY_DESTINATION"
fi

if [ -n "$RELAYHOST" ]; then
  postconf -e "relayhost=$RELAYHOST"

  if [ -n "$RELAYHOST_PASSWORD" ]; then
    # We need a secure channel to send plaintext passwords/apikeys.
    postconf -e smtp_tls_security_level=verify
    # NOTE: Setting tls_append_default_CA=yes doesn't work, for two reasons:
    # 1) The default CA doesn't appear in the chroot.
    # 2) The default CA loading code branch doesn't run unless CAfile or CApath
    #    is set.
    # So, rather than work around all that, we can just ask for the default CA
    # path to be used (and synced to the chroot).
    postconf -e smtp_tls_CApath=/usr/lib/ssl/certs

    postconf -e smtp_sasl_auth_enable=yes
    postconf -e smtp_sasl_tls_verified_security_options=noanonymous
    postconf -e smtp_sasl_password_maps=hash:/etc/postfix/sasl_passwd
    cat >/etc/postfix/sasl_passwd <<EOF
$RELAYHOST       $RELAYHOST_USERNAME:$RELAYHOST_PASSWORD
EOF
    postmap hash:/etc/postfix/sasl_passwd
  fi
fi

if [ "$ROOT_ALIAS" ]; then
  sed -i '/^root:/d' /etc/aliases
  echo "root: $ROOT_ALIAS" >> /etc/aliases
  newaliases
fi

# We have to start and stop postfix first through init.d to populate
# postfix spool directory for chroot in which postfix is running.
/etc/init.d/postfix start
/etc/init.d/postfix abort

# Is there any other script to run here?
[ -f /etc/service/postfix/run.initialization ] && source /etc/service/postfix/run.initialization

exec postfix start-fg 2>&1
